// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'parser.dart';

Future<List<Point3D>> parsePcd({required String path}) => RustLib.instance.api.crateApiParsePcd(path: path);

Future<List<Point3D>> parsePcdData({required String content}) =>
    RustLib.instance.api.crateApiParsePcdData(content: content);
