// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Point3D {
  final double x;
  final double y;
  final double z;
  final int color;
  final bool hasColor;

  const Point3D({required this.x, required this.y, required this.z, required this.color, required this.hasColor});

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ z.hashCode ^ color.hashCode ^ hasColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point3D &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          z == other.z &&
          color == other.color &&
          hasColor == other.hasColor;
}
